name: Deploy Vite to S3

on: workflow_dispatch

permissions:
    id-token: write # Required for OIDC authentication
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1 # Change to your AWS region
            - name: Change directory to frontend project
              run: |
                  cd app
                  npm install
                  npm run build

            - name: Upload to S3
              run: aws s3 sync app/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
            - name: Invalidate CloudFront Cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDRONT_DISTRIBUTION_ID}} --paths "/*"
