name: Deploy AWS CDK Stack

on: workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.actor == 'jwhaley5'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  role-session-name: GitHubActionsSession
                  aws-region: us-east-1

            - name: Install dependencies
              run: npm install -g aws-cdk

            - name: Install project dependencies
              run: npm install

            - name: Deploy CDK Stack
              run: cdk deploy --require-approval never
